# Generated by Django 5.1.1 on 2024-09-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='decsription',
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
